version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile  
    volumes:
      - .:/app
    env_file:
      - ./.env
  web:
    build: ./.docker/nginx
    ports:
      - "8000:80"
      - "4430:443"
    depends_on:
      - app